name: Manual Vercel Deployment

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Vercel
              run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
